apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-proj-deployment

spec:
  selector:
    matchLabels:
      app: django-k8s-proj-deployment
  template:
    metadata:
      labels:
        app: django-k8s-proj-deployment
    spec:
      containers:
        - name: django-k8s-proj
          image: registry.digitalocean.com/django-k8s-po/django-k8s-proj:latest
          envFrom:
            - secretRef:
                name: django-k8s-web-prod-env
          ports:
            - containerPort: 8001
      imagePullSecrets:
        - name: django-k8s-po

---
apiVersion: v1
kind: Service

metadata:
  name: django-k8s-proj-service

spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: django-k8s-proj-deployment
